name: On Commit Dispatch

on:
  repository_dispatch:
    types: [sync-from-ui-commit]

permissions:
  id-token: write
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ui-server
        uses: actions/checkout@v4

      - name: Download and Build UI
        uses: ./.github/actions/download-and-build-ui
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Commit changes
        run: |
          git config --local user.name 'Temporal Data (cicd)'
          git config --local user.email 'commander-data@temporal.io'
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
            echo "changes_committed=false" >> $GITHUB_ENV
            exit 0
          else
            echo "changes_committed=true" >> $GITHUB_ENV
          fi
          git commit -m "Sync from UI commit ${{ github.sha }}"
          git push

  commit:
    uses: ./.github/workflows/on-commit.yaml
    needs: [sync]
    secrets: inherit
    with:
      ref: ${{ needs.sync.outputs.commit_hash }}
      release_tag: ${{ github.event.client_payload.release_tag }}
      release_url: ${{ needs.sync-ui.outputs.release_url }}

