name: On Release Dispatch

on:
  repository_dispatch:
    types: [sync-from-ui-release]

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: write

jobs:
  sync-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ui-server
        uses: actions/checkout@v4

      - name: Download and Build UI
        uses: ./.github/actions/download-and-build-ui
        with:
          ref: ${{ github.event.client_payload.release_tag }}

      # If an action pushes code using the repository’s GITHUB_TOKEN, a new
      # workflow will not run even when the repository contains a workflow
      # configured to run when push events occur.
      - name: Prepare token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.TEMPORAL_CICD_APP_ID }}
          private-key: ${{ secrets.TEMPORAL_CICD_PRIVATE_KEY }}
          permission-contents: write

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git config --local user.name 'Temporal Data (cicd)'
          git config --local user.email 'commander-data@temporal.io'
          git add .
          git commit -m "Sync from UI release ${{ github.event.client_payload.release_tag }}"
          git push

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          append_body: true
          tag_name: ${{ github.event.client_payload.release_tag }}
          name: ${{ github.event.client_payload.release_tag }}
          body: |
            Release synced from [ui@${{ github.event.client_payload.release_tag }}](${{ github.event.client_payload.release_url }})
