name: On Release Dispatch

on:
  repository_dispatch:
    types: [sync-from-ui-release]

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: write

jobs:
  sync-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ui-server
        uses: actions/checkout@v4

      - name: Download and Build UI
        uses: ./.github/actions/download-and-build-ui
        with:
          ref: ${{ github.event.client_payload.release_tag }}

      - name: Commit changes
        id: commit_changes
        run: |
          git config --local user.name 'Temporal Data (cicd)'
          git config --local user.email 'commander-data@temporal.io'
          git add .
          git commit -m "Sync from UI release ${{ github.event.client_payload.release_tag }}"
          git push

          echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          target_commitish: ${{ steps.commit_changes.outputs.commit_hash }}
          generate_release_notes: true
          tag_name: ${{ github.event.client_payload.release_tag }}
          name: ${{ github.event.client_payload.release_tag }}
          body: |
            Release synced from [ui@${{ github.event.client_payload.release_tag }}](${{ github.event.client_payload.release_url }})

